# This is the main pipeline which covers all the stages
# The tasks are stored in pipelines/steps.yml
# you can read more about this:
trigger:
  - master
  - release
  - development

stages:
  - stage: Dev
    displayName: 'Deploying to Development environment'
    jobs:
      - template: pipelines/steps.yml
        parameters:
          environment: Development
          azureSubscription: 'Pay-As-You-Go'
          WorkspaceName: 'az-sentinel-wks' # Enter the Azure Sentinel Workspace name
          SubscriptionId: '252d2f70-7d9d-4811-86f8-45f87d75fbd0'
          ResourceGroupName: 'az-sentinel'
          ResourceGroupLocation: 'australiaeast'
          EnableSentinel: true
          analyticsRulesFile: SettingFiles/AlertRules.json # leave empty if you dont want to configure Analytic rules
          huntingRulesFile: SettingFiles/HuntingRules.json # leave empty if you dont want to configure Hunting rules
          PlaybooksFolder: Playbooks/ # leave empty if you dont want to configure Playbooks
          ConnectorsFile: SettingFiles/DataConnectors.json # leave empty if you dont want to configure Connectors
          WorkbooksFolder: Workbooks/
          WorkbookSourceId: '' # leave empty if you dont want to configure Workbook

 